services:
  Sidus\AdminBundle\Request\ParamConverter\AdminEntityParamConverter:
    autowire: true
    public: false
    tags:
      - { name: request.param_converter, converter: sidus_admin.entity }

  Sidus\AdminBundle\Request\ValueResolver\AdminEntityValueResolver:
    autowire: true
    tags:
        - controller.targeted_value_resolver:
            name: Sidus\AdminBundle\Request\ValueResolver\AdminEntityValueResolver
