# This file contains deprecated service ids that are meant to be removed in future versions

services:
    sidus_admin.configuration.admin.handler:
        alias: Sidus\AdminBundle\Configuration\AdminConfigurationHandler

    sidus_admin.routing.admin_router:
        alias: Sidus\AdminBundle\Routing\AdminRouter

    sidus_admin.entity.matcher:
        alias: Sidus\AdminBundle\Entity\AdminEntityMatcher

    sidus_admin.templating.template_resolver:
        alias: Sidus\AdminBundle\Twig\TemplateResolver
