services:
    Sidus\AdminBundle\Event\AdminControllerInjecter:
        class: Sidus\AdminBundle\Event\AdminControllerInjecter
        public: false
        arguments: ['@Sidus\AdminBundle\Configuration\AdminConfigurationHandler']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
