services:
    sidus_admin.kernel.event.controller_injecter:
        class: Sidus\AdminBundle\Event\AdminControllerInjecter
        arguments: ['@sidus_admin.configuration.admin.handler', '@twig']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
