services:
    Sidus\AdminBundle\Routing\AdminRouteLoader:
        autowire: true
        public: false
        tags:
            - { name: routing.loader }

    Sidus\AdminBundle\Routing\AdminRouter:
        autowire: true
        public: true # This will change in the next version
