services:
    Sidus\AdminBundle\Twig\AdminExtension:
        class: Sidus\AdminBundle\Twig\AdminExtension
        arguments:
            - '@Sidus\AdminBundle\Configuration\AdminConfigurationHandler'
            - '@Sidus\AdminBundle\Entity\AdminEntityMatcher'
            - '@Sidus\AdminBundle\Routing\AdminRouter'
        tags:
            - { name: twig.extension }

    Sidus\AdminBundle\Twig\TemplateResolver:
        class: Sidus\AdminBundle\Twig\TemplateResolver
        arguments:
            - '@Sidus\AdminBundle\Configuration\AdminConfigurationHandler'
            - '@twig'
            - '%sidus_admin.templating.fallback_template_directory%'
            - '@logger'
