services:
    Sidus\AdminBundle\Twig\AdminExtension:
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

    Sidus\AdminBundle\Twig\TemplateResolver:
        autowire: true
        public: true # This will change in the next version
        arguments:
            $globalFallbackTemplate: '%sidus_admin.templating.fallback_template_directory%'
